<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
class RUSPIC_Cat_Shortcodes {
    private $db;
    public function __construct($db){$this->db=$db;add_action('wp_enqueue_scripts',array($this,'assets'));add_shortcode('ruspic_catalog',array($this,'catalog'));add_shortcode('ruspic_product',array($this,'product'));add_shortcode('ruspic_brands',array($this,'brands'));}
    public function assets(){wp_enqueue_style('ruspic-cat-front',RUSPIC_CAT_URL.'assets/css/frontend.css',array(),RUSPIC_CAT_VERSION);wp_enqueue_script('ruspic-cat-front',RUSPIC_CAT_URL.'assets/js/frontend.js',array(),RUSPIC_CAT_VERSION,true);wp_localize_script('ruspic-cat-front','RUSPIC_CAT',array('api'=>esc_url_raw(rest_url('ruspic/v1/')),'nonce'=>wp_create_nonce('wp_rest')));}
    public function catalog($atts=array()){ $atts=shortcode_atts(array('limit'=>24),$atts);$products=$this->db->get_products(array('limit'=>(int)$atts['limit'],'offset'=>0));$brands=$this->db->get_brands(array('limit'=>100));$cats=$this->db->get_all_categories();ob_start();?><section class="ruspic-catalog" data-ruspic-catalog><div class="ruspic-catalog__toolbar"><input data-ruspic-search type="search" placeholder="Поиск по названию или артикулу..."><select data-ruspic-brand><option value="0">Все бренды</option><?php foreach($brands as $b):?><option value="<?php echo (int)$b->id;?>"><?php echo esc_html($b->name);?></option><?php endforeach;?></select><select data-ruspic-category><option value="0">Все категории</option><?php foreach($cats as $c):?><option value="<?php echo (int)$c->id;?>"><?php echo esc_html($c->name);?></option><?php endforeach;?></select></div><div class="ruspic-product-grid" data-ruspic-products><?php echo $this->cards($products);?></div></section><?php return ob_get_clean();}
    private function cards($products){ob_start();foreach($products as $p):?><article class="ruspic-product-card"><div class="ruspic-product-card__body"><div class="ruspic-product-card__meta"><?php echo esc_html($p->brand_name?:'RUSPIC');?></div><h3><a href="<?php echo esc_url(add_query_arg('ruspic_product',(int)$p->id));?>"><?php echo esc_html($p->name);?></a></h3><?php if($p->sku):?><div class="ruspic-sku">Арт. <?php echo esc_html($p->sku);?></div><?php endif;?><p><?php echo esc_html(wp_trim_words(wp_strip_all_tags($p->short_description),18));?></p><div class="ruspic-product-card__bottom"><strong><?php echo $p->price!==null?esc_html(number_format((float)$p->price,2,',',' ').' '.$p->currency):'Цена по запросу';?></strong><button type="button" data-ruspic-add data-id="<?php echo (int)$p->id;?>" data-name="<?php echo esc_attr($p->name);?>">В корзину</button></div></div></article><?php endforeach;if(!$products)echo '<div class="ruspic-empty">Товары не найдены.</div>';return ob_get_clean();}
    public function product($atts=array()){ $id=(int)($_GET['ruspic_product']??($atts['id']??0));if(!$id)return '<p>Не указан товар.</p>';$p=$this->db->get_product($id);if(!$p)return '<p>Товар не найден.</p>';ob_start();?><article class="ruspic-product"><div class="ruspic-product__meta"><?php echo esc_html($p->brand_name?:'');?></div><h1><?php echo esc_html($p->name);?></h1><?php if($p->sku):?><div class="ruspic-sku">Артикул: <?php echo esc_html($p->sku);?></div><?php endif;?><div class="ruspic-product__price"><?php echo $p->price!==null?esc_html(number_format((float)$p->price,2,',',' ').' '.$p->currency):'Цена по запросу';?></div><p><?php echo wp_kses_post(wpautop($p->description));?></p><?php if($p->attributes):?><h2>Характеристики</h2><table class="ruspic-specs"><tbody><?php foreach($p->attributes as $a):?><tr><th><?php echo esc_html($a->name);?></th><td><?php echo esc_html($a->value_text);?><?php if($a->unit)echo ' '.esc_html($a->unit);?></td></tr><?php endforeach;?></tbody></table><?php endif;?><button type="button" class="ruspic-main-button" data-ruspic-add data-id="<?php echo (int)$p->id;?>" data-name="<?php echo esc_attr($p->name);?>">Добавить в корзину</button></article><?php return ob_get_clean();}
    public function brands(){ $brands=$this->db->get_brands(array('limit'=>100));ob_start();?><div class="ruspic-brands"><?php foreach($brands as $b):?><div class="ruspic-brand"><strong><?php echo esc_html($b->name);?></strong><?php if($b->website_url):?><a href="<?php echo esc_url($b->website_url);?>" target="_blank" rel="noopener">Сайт производителя</a><?php endif;?></div><?php endforeach;?></div><?php return ob_get_clean();}
}
