<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

class RUSPIC_Cat_Admin {
    private $db;
    public function __construct( $db ) { $this->db = $db; add_action( 'admin_menu', array( $this, 'menu' ) ); add_action( 'admin_enqueue_scripts', array( $this, 'assets' ) ); }
    public function menu() {
        add_menu_page( 'RUSPIC Cat', 'RUSPIC Cat', 'manage_options', 'ruspic-cat', array( $this, 'dashboard' ), 'dashicons-store', 25 );
        add_submenu_page( 'ruspic-cat', 'Обзор', 'Обзор', 'manage_options', 'ruspic-cat', array( $this, 'dashboard' ) );
        add_submenu_page( 'ruspic-cat', 'Товары', 'Товары', 'manage_options', 'ruspic-cat-products', array( $this, 'products' ) );
        add_submenu_page( 'ruspic-cat', 'Импорт из парсинга', 'Импорт из парсинга', 'manage_options', 'ruspic-cat-parser-import', array( $this, 'parser_import' ) );
        add_submenu_page( 'ruspic-cat', 'Бренды', 'Бренды', 'manage_options', 'ruspic-cat-brands', array( $this, 'brands' ) );
        add_submenu_page( 'ruspic-cat', 'Категории', 'Категории', 'manage_options', 'ruspic-cat-categories', array( $this, 'categories' ) );
        add_submenu_page( 'ruspic-cat', 'Характеристики', 'Характеристики', 'manage_options', 'ruspic-cat-attributes', array( $this, 'attributes' ) );
        add_submenu_page( 'ruspic-cat', 'Заявки', 'Заявки', 'manage_options', 'ruspic-cat-orders', array( $this, 'orders' ) );
    }
    public function assets( $hook ) { if ( strpos( $hook, 'ruspic-cat' ) === false ) return; wp_enqueue_style( 'ruspic-cat-admin', RUSPIC_CAT_URL.'assets/css/admin.css', array(), RUSPIC_CAT_VERSION ); wp_enqueue_media(); wp_enqueue_script( 'ruspic-cat-admin', RUSPIC_CAT_URL.'assets/js/admin.js', array('jquery'), RUSPIC_CAT_VERSION, true ); }
    private function header( $title, $subtitle='' ) { echo '<div class="wrap ruspic-cat-admin"><h1>'.$this->esc($title).'</h1>'; if($subtitle)echo '<p class="description">'.$this->esc($subtitle).'</p>'; }
    private function footer(){echo '</div>';}
    private function esc($s){return esc_html($s);}
    private function notice(){ if(!empty($_GET['ruspic_saved']))echo '<div class="notice notice-success is-dismissible"><p>Изменения сохранены.</p></div>'; if(!empty($_GET['ruspic_deleted']))echo '<div class="notice notice-success is-dismissible"><p>Запись удалена.</p></div>'; }
    private function redirect($page,$key='ruspic_saved'){wp_safe_redirect(admin_url('admin.php?page='.$page.'&'.$key.'=1'));exit;}
    private function handle_actions(){
        if(!current_user_can('manage_options'))return;
        if(empty($_POST['ruspic_action']))return;
        check_admin_referer('ruspic_cat_admin');$action=sanitize_key($_POST['ruspic_action']);
        if($action==='save_brand'){$id=(int)($_POST['id']??0);$this->db->save_brand($_POST,$id);$this->redirect('ruspic-cat-brands');}
        if($action==='delete_brand'){$this->db->delete_brand((int)$_POST['id']);$this->redirect('ruspic-cat-brands','ruspic_deleted');}
        if($action==='save_category'){$id=(int)($_POST['id']??0);$this->db->save_category($_POST,$id);$this->redirect('ruspic-cat-categories');}
        if($action==='delete_category'){$r=$this->db->delete_category((int)$_POST['id']);if(is_wp_error($r))wp_die(esc_html($r->get_error_message()));$this->redirect('ruspic-cat-categories','ruspic_deleted');}
        if($action==='save_attribute'){$this->db->save_attribute($_POST,(int)($_POST['id']??0));$this->redirect('ruspic-cat-attributes');}
        if($action==='save_product'){$attrs=array();foreach((array)($_POST['attr_id']??array()) as $i=>$aid){$attrs[]=array('attribute_id'=>(int)$aid,'value'=>sanitize_text_field($_POST['attr_value'][$i]??''));}$_POST['attributes']=$attrs;$this->db->save_product($_POST,(int)($_POST['id']??0));$this->redirect('ruspic-cat-products');}
        if($action==='delete_product'){$this->db->delete_product((int)$_POST['id']);$this->redirect('ruspic-cat-products','ruspic_deleted');}
        if($action==='parser_import'){$this->handle_parser_import();}
    }
    private function handle_parser_import(){
        if(empty($_FILES['parser_file'])){$this->redirect('ruspic-cat-parser-import','ruspic_import_error');}
        $status=in_array(($_POST['parser_status']??'publish'),array('draft','publish'),true)?$_POST['parser_status']:'publish';
        $result=$this->db_parser_import()->import($_FILES['parser_file'],array('status'=>$status));
        if(is_wp_error($result))wp_die(esc_html($result->get_error_message()));
        wp_safe_redirect(admin_url('admin.php?page=ruspic-cat-parser-import&ruspic_imported=1&processed='.(int)$result['processed'].'&created='.(int)$result['created'].'&updated='.(int)$result['updated'].'&failed='.(int)$result['failed']));exit;
    }
    private function db_parser_import(){static $service=null;if(!$service)$service=new RUSPIC_Cat_Parser_Import($this->db);return $service;}
    public function dashboard(){ $this->handle_actions();$this->header('RUSPIC Cat','Независимый каталог и собственная корзина-заявка. WooCommerce не требуется.');$this->notice();$stats=array('Товары'=>$this->db->count('products'),'Бренды'=>$this->db->count('brands'),'Категории'=>$this->db->count('categories'),'Характеристики'=>$this->db->count('attributes'),'Заявки'=>$this->db->count('orders'));echo '<div class="ruspic-stats">';foreach($stats as $k=>$v)echo '<div class="ruspic-stat"><strong>'.(int)$v.'</strong><span>'.$this->esc($k).'</span></div>';echo '</div><div class="ruspic-card"><h2>Быстрый старт</h2><ol><li>Создайте бренды.</li><li>Постройте дерево категорий.</li><li>Добавьте характеристики.</li><li>Загрузите товары.</li><li>Разместите шорткод <code>[ruspic_catalog]</code> на странице каталога.</li><li>Разместите <code>[ruspic_cart]</code> на странице корзины.</li></ol></div><div class="ruspic-card"><h2>REST API</h2><p>Публичная точка: <code>/wp-json/ruspic/v1/</code></p><p>Примеры: <code>GET /products</code>, <code>GET /products/1</code>, <code>GET /brands</code>, <code>GET /categories</code>.</p></div>';$this->footer(); }
    public function parser_import(){
        $this->handle_actions();$this->header('Импорт из парсинга','Загрузка CSV, сформированного парсером, напрямую в таблицы RUSPIC Cat.');
        if(isset($_GET['ruspic_imported']))echo '<div class="notice notice-success is-dismissible"><p>Импорт завершён: обработано '.(int)($_GET['processed']??0).', создано '.(int)($_GET['created']??0).', обновлено '.(int)($_GET['updated']??0).', ошибок '.(int)($_GET['failed']??0).'.</p></div>';
        if(isset($_GET['ruspic_import_error']))echo '<div class="notice notice-error is-dismissible"><p>Файл импорта не получен.</p></div>';
        echo '<div class="ruspic-card"><h2>Импорт каталога из парсинга</h2><p>Категория <strong>не задаётся вручную</strong>. Импортер сначала ищет в CSV колонки <code>Category</code>, <code>Categories</code> или <code>Category path</code>. Если их нет, он определяет дерево категорий по <code>Product URL</code>. Для techelectro.ru URL вида <code>/prod/cable-lugs/cu/tmlu/sku_101403/</code> превращается в дерево «Кабельные наконечники, гильзы, сжимы → Медные наконечники и гильзы → ТМЛ-У».</p><form method="post" enctype="multipart/form-data">'.$this->nonce().'<input type="hidden" name="ruspic_action" value="parser_import"><p><label>CSV-файл<input class="widefat" type="file" name="parser_file" accept=".csv,text/csv" required></label></p><p><label>Статус<select name="parser_status"><option value="publish">Опубликован</option><option value="draft">Черновик</option></select></label></p><p><button class="button button-primary button-large">Импортировать из парсинга</button></p></form></div><div class="ruspic-card"><h2>Формат файла techelectro_woocommerce.csv</h2><p>Поддержаны поля SKU, Name, Short description, Description, Images, Regular price, Technical specifications, EAN-13 и Product URL. Характеристики из HTML-таблицы автоматически превращаются в характеристики RUSPIC Cat.</p></div>';
        $this->footer();
    }
    public function brands(){ $this->handle_actions();$this->header('Бренды','Производители и торговые марки.');$this->notice();$edit=null;if(!empty($_GET['edit']))$edit=$this->db->get_brand((int)$_GET['edit']);echo '<div class="ruspic-grid"><div class="ruspic-card"><h2>'.($edit?'Редактировать бренд':'Новый бренд').'</h2><form method="post">'.$this->nonce().'<input type="hidden" name="ruspic_action" value="save_brand"><input type="hidden" name="id" value="'.(int)($edit->id??0).'">';$this->input('name','Название',$edit->name??'');$this->input('slug','Slug',$edit->slug??'');$this->textarea('description','Описание',$edit->description??'');$this->input('website_url','Сайт',$edit->website_url??'');$this->media_field('logo_id','Логотип',($edit->logo_id??0));echo '<p><button class="button button-primary">Сохранить</button></p></form></div><div class="ruspic-card"><h2>Список брендов</h2><table class="widefat striped"><thead><tr><th>Бренд</th><th>Сайт</th><th>Действия</th></tr></thead><tbody>';foreach($this->db->get_brands(array('limit'=>100)) as $b){echo '<tr><td><strong>'.$this->esc($b->name).'</strong></td><td>'.($b->website_url?'<a target="_blank" href="'.esc_url($b->website_url).'">Открыть</a>':'—').'</td><td><a href="'.esc_url(admin_url('admin.php?page=ruspic-cat-brands&edit='.$b->id)).'">Изменить</a> · '.$this->delete_form('delete_brand',$b->id).'</td></tr>';}echo '</tbody></table></div></div>';$this->footer(); }
    public function categories(){ $this->handle_actions();$this->header('Категории','Иерархическое дерево каталога.');$this->notice();$edit=null;if(!empty($_GET['edit']))$edit=$this->db->get_category((int)$_GET['edit']);$cats=$this->db->get_all_categories();echo '<div class="ruspic-grid"><div class="ruspic-card"><h2>'.($edit?'Редактировать категорию':'Новая категория').'</h2><form method="post">'.$this->nonce().'<input type="hidden" name="ruspic_action" value="save_category"><input type="hidden" name="id" value="'.(int)($edit->id??0).'">';$this->input('name','Название',$edit->name??'');$this->input('slug','Slug',$edit->slug??'');echo '<p><label>Родитель<select name="parent_id"><option value="0">— Верхний уровень —</option>';foreach($cats as $c)if((int)$c->id!==(int)($edit->id??0))echo '<option value="'.(int)$c->id.'" '.selected((int)($edit->parent_id??0),(int)$c->id,false).'>'.esc_html($this->category_label($c,$cats)).'</option>';echo '</select></label></p>';$this->textarea('description','Описание',$edit->description??'');$this->media_field('image_id','Изображение категории',($edit->image_id??0));$this->input('sort_order','Порядок',$edit->sort_order??0,'number');echo '<p><button class="button button-primary">Сохранить</button></p></form></div><div class="ruspic-card"><h2>Дерево категорий</h2><table class="widefat striped"><thead><tr><th>Категория</th><th>Slug</th><th></th></tr></thead><tbody>';foreach($cats as $c){echo '<tr><td><strong>'.esc_html($this->category_label($c,$cats)).'</strong></td><td><code>'.esc_html($c->slug).'</code></td><td><a href="'.esc_url(admin_url('admin.php?page=ruspic-cat-categories&edit='.$c->id)).'">Изменить</a> · '.$this->delete_form('delete_category',$c->id).'</td></tr>';}echo '</tbody></table></div></div>';$this->footer(); }
    private function category_label($c,$cats){$level=0;$parent=(int)$c->parent_id;while($parent&&$level<20){foreach($cats as $x){if((int)$x->id===$parent){$level++;$parent=(int)$x->parent_id;break;}}if($parent===(int)$c->parent_id)break;}return str_repeat('— ',$level).$c->name;}
    public function attributes(){ $this->handle_actions();$this->header('Характеристики','Атрибуты, которые можно назначать товарам.');$this->notice();echo '<div class="ruspic-grid"><div class="ruspic-card"><h2>Новая характеристика</h2><form method="post">'.$this->nonce().'<input type="hidden" name="ruspic_action" value="save_attribute">';$this->input('name','Название');$this->input('slug','Slug');$this->input('unit','Единица измерения');echo '<p><label>Тип<select name="type"><option value="text">Текст</option><option value="number">Число</option><option value="select">Список</option><option value="boolean">Да/нет</option></select></label></p><p><button class="button button-primary">Добавить</button></p></form></div><div class="ruspic-card"><h2>Характеристики</h2><table class="widefat striped"><thead><tr><th>Название</th><th>Slug</th><th>Ед.</th><th>Тип</th></tr></thead><tbody>';foreach($this->db->get_attributes() as $a)echo '<tr><td>'.esc_html($a->name).'</td><td><code>'.esc_html($a->slug).'</code></td><td>'.esc_html($a->unit).'</td><td>'.esc_html($a->type).'</td></tr>';echo '</tbody></table></div></div>';$this->footer(); }
    public function products(){
        $this->handle_actions();$this->header('Товары','Основной каталог RUSPIC.');$this->notice();
        $edit=null;if(isset($_GET['edit']))$edit=$this->db->get_product((int)$_GET['edit']);
        if(isset($edit->attributes)){$map=array();foreach($edit->attributes as $a)$map[$a->attribute_id]=$a->value_text;}else{$map=array();}
        if($edit){$this->product_form($edit,$map);}else{
            $rows=$this->db->get_products(array('limit'=>100));$cats=$this->db->get_all_categories();
            echo '<div class="ruspic-card"><p><a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=ruspic-cat-products&edit=0')).'">Добавить товар</a></p><table class="widefat striped ruspic-products-table"><thead><tr><th>Фото</th><th>Товар</th><th>Артикул</th><th>Бренд</th><th>Категория / подкатегории</th><th>Цена</th><th></th></tr></thead><tbody>';
            foreach($rows as $p){
                $thumb=$p->image_id?wp_get_attachment_image((int)$p->image_id,'thumbnail',false,array('style'=>'width:56px;height:56px;object-fit:cover;border-radius:6px;display:block;')):'<span class="ruspic-no-image">—</span>';
                echo '<tr><td>'.$thumb.'</td><td><strong>'.esc_html($p->name).'</strong></td><td>'.esc_html($p->sku).'</td><td>'.esc_html($p->brand_name?:'—').'</td><td>'.esc_html($this->category_path_label((int)$p->category_id,$cats)).'</td><td>'.($p->price!==null?esc_html(number_format((float)$p->price,2,',',' ').' '.$p->currency):'По запросу').'</td><td><a href="'.esc_url(admin_url('admin.php?page=ruspic-cat-products&edit='.$p->id)).'">Изменить</a> · '.$this->delete_form('delete_product',$p->id).'</td></tr>';
            }
            echo '</tbody></table></div>';
        }$this->footer();
    }
    private function product_form($p,$map){$brands=$this->db->get_brands(array('limit'=>100));$cats=$this->db->get_all_categories();$attrs=$this->db->get_attributes();echo '<div class="ruspic-card"><h2>'.($p?'Редактировать товар':'Новый товар').'</h2><form method="post">'.$this->nonce().'<input type="hidden" name="ruspic_action" value="save_product"><input type="hidden" name="id" value="'.(int)($p->id??0).'">';$this->input('name','Название',$p->name??'');$this->input('slug','Slug',$p->slug??'');$this->input('sku','Артикул / SKU',$p->sku??'');$this->media_field('image_id','Главное изображение',($p->image_id??0));echo '<div class="ruspic-two"><p><label>Бренд<select name="brand_id"><option value="0">— Не выбран —</option>';foreach($brands as $b)echo '<option value="'.(int)$b->id.'" '.selected((int)($p->brand_id??0),(int)$b->id,false).'>'.esc_html($b->name).'</option>';echo '</select></label></p><p><label>Категория<select name="category_id"><option value="0">— Не выбрана —</option>';foreach($cats as $c)echo '<option value="'.(int)$c->id.'" '.selected((int)($p->category_id??0),(int)$c->id,false).'>'.esc_html($this->category_label($c,$cats)).'</option>';echo '</select></label></p></div>';$this->textarea('short_description','Краткое описание',$p->short_description??'');$this->textarea('description','Описание',$p->description??'');echo '<div class="ruspic-two">';$this->input('price','Цена',$p->price??'','number','step="0.01"');$this->input('currency','Валюта',$p->currency??'RUB');echo '</div><div class="ruspic-two">';echo '<p><label>Наличие<select name="stock_status"><option value="in_stock" '.selected($p->stock_status??'in_stock','in_stock',false).'>В наличии</option><option value="on_order" '.selected($p->stock_status??'','on_order',false).'>Под заказ</option><option value="out_of_stock" '.selected($p->stock_status??'','out_of_stock',false).'>Нет в наличии</option><option value="unknown" '.selected($p->stock_status??'','unknown',false).'>Уточняется</option></select></label></p>';$this->input('stock_qty','Количество',$p->stock_qty??'','number','step="0.001"');echo '</div><h3>Характеристики</h3><table class="widefat"><thead><tr><th>Характеристика</th><th>Значение</th></tr></thead><tbody>';foreach($attrs as $a)echo '<tr><td>'.esc_html($a->name).' '.($a->unit?'('.esc_html($a->unit).')':'').'<input type="hidden" name="attr_id[]" value="'.(int)$a->id.'"></td><td><input type="text" name="attr_value[]" value="'.esc_attr($map[$a->id]??'').'" class="widefat"></td></tr>';echo '</tbody></table><p><label><input type="checkbox" name="featured" value="1" '.checked(!empty($p->featured),true,false).'> Показывать среди рекомендуемых</label></p><p><button class="button button-primary">Сохранить товар</button> <a class="button" href="'.esc_url(admin_url('admin.php?page=ruspic-cat-products')).'">Назад</a></p></form></div>';}
    public function orders(){ $this->header('Заявки','Заказы корзины-заявки без онлайн-оплаты.');$this->notice();$orders=$this->db->get_orders();echo '<div class="ruspic-card"><table class="widefat striped"><thead><tr><th>#</th><th>Дата</th><th>Клиент</th><th>Контакты</th><th>Статус</th></tr></thead><tbody>';foreach($orders as $o)echo '<tr><td><strong>'.(int)$o->id.'</strong></td><td>'.esc_html($o->created_at).'</td><td>'.esc_html($o->customer_name).'</td><td>'.esc_html($o->customer_phone).' '.esc_html($o->customer_email).'</td><td>'.esc_html($o->status).'</td></tr>';echo '</tbody></table></div>';$this->footer(); }
    private function category_path_label($id,$cats){
        if(!$id)return '—';$by_id=array();foreach($cats as $c)$by_id[(int)$c->id]=$c;$parts=array();$guard=0;$current=$id;
        while($current&&isset($by_id[$current])&&$guard<30){$c=$by_id[$current];array_unshift($parts,$c->name);$current=(int)$c->parent_id;$guard++;}
        return $parts?implode(' → ',$parts):'—';
    }
    private function media_field($name,$label,$id=0){
        $id=(int)$id;$url=$id?wp_get_attachment_image_url($id,'thumbnail'):'';
        echo '<p><label>'.esc_html($label).'</label><span class="ruspic-media-field"><input type="hidden" name="'.esc_attr($name).'" value="'.$id.'"><button type="button" class="button ruspic-media-select" data-target="'.esc_attr($name).'">Выбрать изображение</button><span class="ruspic-media-preview">'.($url?'<img src="'.esc_url($url).'" alt="">':'').'</span></span></p>';
    }
    private function nonce(){return wp_nonce_field('ruspic_cat_admin','_wpnonce',true,false);}
    private function input($name,$label,$value='',$type='text',$extra=''){echo '<p><label>'.esc_html($label).'<input class="widefat" type="'.esc_attr($type).'" name="'.esc_attr($name).'" value="'.esc_attr($value).'" '.$extra.'></label></p>';}
    private function textarea($name,$label,$value=''){echo '<p><label>'.esc_html($label).'<textarea class="widefat" rows="5" name="'.esc_attr($name).'">'.esc_textarea($value).'</textarea></label></p>';}
    private function delete_form($action,$id){return '<form class="ruspic-inline" method="post">'.$this->nonce().'<input type="hidden" name="ruspic_action" value="'.esc_attr($action).'"><input type="hidden" name="id" value="'.(int)$id.'"><button class="button-link-delete" onclick="return confirm(\'Удалить запись?\')">Удалить</button></form>';}
}
